CREATE TYPE "content_status" AS ENUM (
  'draft',
  'published',
  'archived'
);

CREATE TYPE "lead_status" AS ENUM (
  'new',
  'contacted',
  'qualified',
  'closed'
);

CREATE TYPE "subscriber_status" AS ENUM (
  'subscribed',
  'unsubscribed'
);

CREATE TYPE "job_status" AS ENUM (
  'draft',
  'published',
  'closed'
);

CREATE TYPE "ad_status" AS ENUM (
  'active',
  'paused',
  'archived'
);

CREATE TABLE "users" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "email" text UNIQUE NOT NULL,
  "password_hash" text NOT NULL,
  "full_name" text NOT NULL,
  "avatar_asset_id" bigint,
  "is_active" boolean NOT NULL DEFAULT true,
  "last_login_at" timestamptz,
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  "updated_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "roles" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" text UNIQUE NOT NULL
);

CREATE TABLE "user_roles" (
  "user_id" bigint,
  "role_id" int,
  PRIMARY KEY ("user_id", "role_id")
);

CREATE TABLE "refresh_tokens" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" bigint NOT NULL,
  "token_hash" text UNIQUE NOT NULL,
  "expires_at" timestamptz NOT NULL,
  "revoked_at" timestamptz,
  "created_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "media_assets" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "provider" text NOT NULL DEFAULT 'local',
  "storage_path" text NOT NULL,
  "filename" text NOT NULL,
  "mime_type" text NOT NULL,
  "size_bytes" bigint NOT NULL,
  "width" int,
  "height" int,
  "alt_text" text,
  "created_by" bigint,
  "created_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "categories" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "locale" text NOT NULL DEFAULT 'en',
  "kind" text NOT NULL,
  "name" text NOT NULL,
  "slug" text NOT NULL,
  "description" text,
  "icon_asset_id" bigint,
  "sort_order" int NOT NULL DEFAULT 0,
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  "updated_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "tags" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "locale" text NOT NULL DEFAULT 'en',
  "name" text NOT NULL,
  "slug" text NOT NULL,
  "created_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "posts" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "locale" text NOT NULL DEFAULT 'en',
  "title" text NOT NULL,
  "slug" text NOT NULL,
  "excerpt" text,
  "content_md" text NOT NULL,
  "hero_asset_id" bigint,
  "og_asset_id" bigint,
  "author_id" bigint,
  "status" content_status NOT NULL DEFAULT 'draft',
  "published_at" timestamptz,
  "seo_title" text,
  "seo_description" text,
  "canonical_url" text,
  "created_by" bigint,
  "updated_by" bigint,
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  "updated_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "post_categories" (
  "post_id" bigint,
  "category_id" bigint,
  PRIMARY KEY ("post_id", "category_id")
);

CREATE TABLE "post_tags" (
  "post_id" bigint,
  "tag_id" bigint,
  PRIMARY KEY ("post_id", "tag_id")
);

CREATE TABLE "post_related" (
  "post_id" bigint,
  "related_post_id" bigint,
  "sort_order" int NOT NULL DEFAULT 0,
  PRIMARY KEY ("post_id", "related_post_id")
);

CREATE TABLE "services" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "locale" text NOT NULL DEFAULT 'en',
  "title" text NOT NULL,
  "slug" text NOT NULL,
  "excerpt" text,
  "content_md" text NOT NULL,
  "hero_asset_id" bigint,
  "og_asset_id" bigint,
  "status" content_status NOT NULL DEFAULT 'draft',
  "published_at" timestamptz,
  "seo_title" text,
  "seo_description" text,
  "canonical_url" text,
  "sort_order" int NOT NULL DEFAULT 0,
  "created_by" bigint,
  "updated_by" bigint,
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  "updated_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "service_categories" (
  "service_id" bigint,
  "category_id" bigint,
  PRIMARY KEY ("service_id", "category_id")
);

CREATE TABLE "service_tags" (
  "service_id" bigint,
  "tag_id" bigint,
  PRIMARY KEY ("service_id", "tag_id")
);

CREATE TABLE "service_deliverables" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "service_id" bigint NOT NULL,
  "title" text NOT NULL,
  "description" text,
  "icon_asset_id" bigint,
  "sort_order" int NOT NULL DEFAULT 0
);

CREATE TABLE "service_process_steps" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "service_id" bigint NOT NULL,
  "title" text NOT NULL,
  "description" text,
  "sort_order" int NOT NULL DEFAULT 0
);

CREATE TABLE "service_faqs" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "service_id" bigint NOT NULL,
  "question" text NOT NULL,
  "answer" text NOT NULL,
  "sort_order" int NOT NULL DEFAULT 0
);

CREATE TABLE "service_related" (
  "service_id" bigint,
  "related_service_id" bigint,
  "sort_order" int NOT NULL DEFAULT 0,
  PRIMARY KEY ("service_id", "related_service_id")
);

CREATE TABLE "service_related_posts" (
  "service_id" bigint,
  "post_id" bigint,
  "sort_order" int NOT NULL DEFAULT 0,
  PRIMARY KEY ("service_id", "post_id")
);

CREATE TABLE "case_studies" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "locale" text NOT NULL DEFAULT 'en',
  "title" text NOT NULL,
  "slug" text NOT NULL,
  "excerpt" text,
  "content_md" text NOT NULL,
  "hero_asset_id" bigint,
  "status" content_status NOT NULL DEFAULT 'draft',
  "published_at" timestamptz,
  "seo_title" text,
  "seo_description" text,
  "created_by" bigint,
  "updated_by" bigint,
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  "updated_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "case_study_metrics" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "case_study_id" bigint NOT NULL,
  "label" text NOT NULL,
  "value" text NOT NULL,
  "sort_order" int NOT NULL DEFAULT 0
);

CREATE TABLE "service_case_studies" (
  "service_id" bigint,
  "case_study_id" bigint,
  "sort_order" int NOT NULL DEFAULT 0,
  PRIMARY KEY ("service_id", "case_study_id")
);

CREATE TABLE "job_posts" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "locale" text NOT NULL DEFAULT 'en',
  "title" text NOT NULL,
  "slug" text NOT NULL,
  "department" text,
  "location" text,
  "employment_type" text,
  "level" text,
  "summary" text,
  "responsibilities_md" text,
  "requirements_md" text,
  "status" job_status NOT NULL DEFAULT 'draft',
  "published_at" timestamptz,
  "created_by" bigint,
  "updated_by" bigint,
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  "updated_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "job_applications" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "job_id" bigint NOT NULL,
  "full_name" text NOT NULL,
  "email" text NOT NULL,
  "phone" text,
  "resume_asset_id" bigint,
  "cover_letter" text,
  "status" text NOT NULL DEFAULT 'new',
  "created_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "leads" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "full_name" text NOT NULL,
  "email" text NOT NULL,
  "phone" text,
  "company" text,
  "message" text,
  "source_path" text,
  "utm_source" text,
  "utm_medium" text,
  "utm_campaign" text,
  "status" lead_status NOT NULL DEFAULT 'new',
  "created_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "newsletter_subscribers" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "email" text UNIQUE NOT NULL,
  "status" subscriber_status NOT NULL DEFAULT 'subscribed',
  "source_path" text,
  "subscribed_at" timestamptz NOT NULL DEFAULT (now()),
  "unsubscribed_at" timestamptz
);

CREATE TABLE "ads" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" text NOT NULL,
  "image_asset_id" bigint,
  "target_url" text NOT NULL,
  "placement" text NOT NULL,
  "status" ad_status NOT NULL DEFAULT 'active',
  "starts_at" timestamptz,
  "ends_at" timestamptz,
  "sort_order" int NOT NULL DEFAULT 0,
  "created_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "pages" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "locale" text NOT NULL DEFAULT 'en',
  "slug" text NOT NULL,
  "title" text NOT NULL,
  "seo_title" text,
  "seo_description" text,
  "hero_asset_id" bigint,
  "status" content_status NOT NULL DEFAULT 'draft',
  "updated_by" bigint,
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  "updated_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "page_sections" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "page_id" bigint NOT NULL,
  "section_key" text NOT NULL,
  "payload" jsonb NOT NULL,
  "sort_order" int NOT NULL DEFAULT 0
);

CREATE TABLE "nav_items" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "locale" text NOT NULL DEFAULT 'en',
  "placement" text NOT NULL,
  "label" text NOT NULL,
  "href" text NOT NULL,
  "sort_order" int NOT NULL DEFAULT 0,
  "parent_id" bigint
);

CREATE TABLE "site_settings" (
  "key" text PRIMARY KEY,
  "value" jsonb NOT NULL,
  "updated_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE INDEX "idx_media_created_at" ON "media_assets" ("created_at");

CREATE UNIQUE INDEX "uq_categories_locale_kind_slug" ON "categories" ("locale", "kind", "slug");

CREATE INDEX "idx_categories_kind_sort" ON "categories" ("kind", "sort_order");

CREATE UNIQUE INDEX "uq_tags_locale_slug" ON "tags" ("locale", "slug");

CREATE UNIQUE INDEX "uq_posts_locale_slug" ON "posts" ("locale", "slug");

CREATE INDEX "idx_posts_status_published_at" ON "posts" ("status", "published_at");

CREATE INDEX "idx_posts_author" ON "posts" ("author_id");

CREATE UNIQUE INDEX "uq_services_locale_slug" ON "services" ("locale", "slug");

CREATE INDEX "idx_services_status_published_at" ON "services" ("status", "published_at");

CREATE INDEX "idx_services_sort_order" ON "services" ("sort_order");

CREATE INDEX "idx_service_deliverables_order" ON "service_deliverables" ("service_id", "sort_order");

CREATE INDEX "idx_service_process_order" ON "service_process_steps" ("service_id", "sort_order");

CREATE INDEX "idx_service_faqs_order" ON "service_faqs" ("service_id", "sort_order");

CREATE UNIQUE INDEX "uq_case_studies_locale_slug" ON "case_studies" ("locale", "slug");

CREATE INDEX "idx_case_studies_status_published_at" ON "case_studies" ("status", "published_at");

CREATE UNIQUE INDEX "uq_job_posts_locale_slug" ON "job_posts" ("locale", "slug");

CREATE INDEX "idx_job_posts_status_published_at" ON "job_posts" ("status", "published_at");

CREATE INDEX "idx_job_applications_job_created" ON "job_applications" ("job_id", "created_at");

CREATE INDEX "idx_leads_status_created" ON "leads" ("status", "created_at");

CREATE INDEX "idx_ads_active" ON "ads" ("status", "placement", "sort_order");

CREATE UNIQUE INDEX "uq_pages_locale_slug" ON "pages" ("locale", "slug");

CREATE INDEX "idx_page_sections_order" ON "page_sections" ("page_id", "sort_order");

CREATE INDEX "idx_nav_items_order" ON "nav_items" ("locale", "placement", "sort_order");

ALTER TABLE "users" ADD FOREIGN KEY ("avatar_asset_id") REFERENCES "media_assets" ("id");

ALTER TABLE "media_assets" ADD FOREIGN KEY ("created_by") REFERENCES "users" ("id");

ALTER TABLE "user_roles" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "user_roles" ADD FOREIGN KEY ("role_id") REFERENCES "roles" ("id");

ALTER TABLE "refresh_tokens" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "categories" ADD FOREIGN KEY ("icon_asset_id") REFERENCES "media_assets" ("id");

ALTER TABLE "posts" ADD FOREIGN KEY ("hero_asset_id") REFERENCES "media_assets" ("id");

ALTER TABLE "posts" ADD FOREIGN KEY ("og_asset_id") REFERENCES "media_assets" ("id");

ALTER TABLE "posts" ADD FOREIGN KEY ("author_id") REFERENCES "users" ("id");

ALTER TABLE "posts" ADD FOREIGN KEY ("created_by") REFERENCES "users" ("id");

ALTER TABLE "posts" ADD FOREIGN KEY ("updated_by") REFERENCES "users" ("id");

ALTER TABLE "post_categories" ADD FOREIGN KEY ("post_id") REFERENCES "posts" ("id");

ALTER TABLE "post_categories" ADD FOREIGN KEY ("category_id") REFERENCES "categories" ("id");

ALTER TABLE "post_tags" ADD FOREIGN KEY ("post_id") REFERENCES "posts" ("id");

ALTER TABLE "post_tags" ADD FOREIGN KEY ("tag_id") REFERENCES "tags" ("id");

ALTER TABLE "post_related" ADD FOREIGN KEY ("post_id") REFERENCES "posts" ("id");

ALTER TABLE "post_related" ADD FOREIGN KEY ("related_post_id") REFERENCES "posts" ("id");

ALTER TABLE "services" ADD FOREIGN KEY ("hero_asset_id") REFERENCES "media_assets" ("id");

ALTER TABLE "services" ADD FOREIGN KEY ("og_asset_id") REFERENCES "media_assets" ("id");

ALTER TABLE "services" ADD FOREIGN KEY ("created_by") REFERENCES "users" ("id");

ALTER TABLE "services" ADD FOREIGN KEY ("updated_by") REFERENCES "users" ("id");

ALTER TABLE "service_categories" ADD FOREIGN KEY ("service_id") REFERENCES "services" ("id");

ALTER TABLE "service_categories" ADD FOREIGN KEY ("category_id") REFERENCES "categories" ("id");

ALTER TABLE "service_tags" ADD FOREIGN KEY ("service_id") REFERENCES "services" ("id");

ALTER TABLE "service_tags" ADD FOREIGN KEY ("tag_id") REFERENCES "tags" ("id");

ALTER TABLE "service_deliverables" ADD FOREIGN KEY ("service_id") REFERENCES "services" ("id");

ALTER TABLE "service_deliverables" ADD FOREIGN KEY ("icon_asset_id") REFERENCES "media_assets" ("id");

ALTER TABLE "service_process_steps" ADD FOREIGN KEY ("service_id") REFERENCES "services" ("id");

ALTER TABLE "service_faqs" ADD FOREIGN KEY ("service_id") REFERENCES "services" ("id");

ALTER TABLE "service_related" ADD FOREIGN KEY ("service_id") REFERENCES "services" ("id");

ALTER TABLE "service_related" ADD FOREIGN KEY ("related_service_id") REFERENCES "services" ("id");

ALTER TABLE "service_related_posts" ADD FOREIGN KEY ("service_id") REFERENCES "services" ("id");

ALTER TABLE "service_related_posts" ADD FOREIGN KEY ("post_id") REFERENCES "posts" ("id");

ALTER TABLE "case_studies" ADD FOREIGN KEY ("hero_asset_id") REFERENCES "media_assets" ("id");

ALTER TABLE "case_studies" ADD FOREIGN KEY ("created_by") REFERENCES "users" ("id");

ALTER TABLE "case_studies" ADD FOREIGN KEY ("updated_by") REFERENCES "users" ("id");

ALTER TABLE "case_study_metrics" ADD FOREIGN KEY ("case_study_id") REFERENCES "case_studies" ("id");

ALTER TABLE "service_case_studies" ADD FOREIGN KEY ("service_id") REFERENCES "services" ("id");

ALTER TABLE "service_case_studies" ADD FOREIGN KEY ("case_study_id") REFERENCES "case_studies" ("id");

ALTER TABLE "job_posts" ADD FOREIGN KEY ("created_by") REFERENCES "users" ("id");

ALTER TABLE "job_posts" ADD FOREIGN KEY ("updated_by") REFERENCES "users" ("id");

ALTER TABLE "job_applications" ADD FOREIGN KEY ("job_id") REFERENCES "job_posts" ("id");

ALTER TABLE "job_applications" ADD FOREIGN KEY ("resume_asset_id") REFERENCES "media_assets" ("id");

ALTER TABLE "ads" ADD FOREIGN KEY ("image_asset_id") REFERENCES "media_assets" ("id");

ALTER TABLE "pages" ADD FOREIGN KEY ("hero_asset_id") REFERENCES "media_assets" ("id");

ALTER TABLE "pages" ADD FOREIGN KEY ("updated_by") REFERENCES "users" ("id");

ALTER TABLE "page_sections" ADD FOREIGN KEY ("page_id") REFERENCES "pages" ("id");

ALTER TABLE "nav_items" ADD FOREIGN KEY ("parent_id") REFERENCES "nav_items" ("id");
