import fs from 'node:fs';
import path from 'node:path';

/**
 * Generate data-driven i18n helpers from JSON dictionaries.
 *
 * Why this exists:
 * - Next.js/TypeScript needs to know dictionary modules at build time.
 * - This script makes locale support "drop-in": adding `src/i18n/dictionaries/<locale>.json`
 *   is enough; no code changes required.
 *
 * Output:
 * - `src/i18n/generated.ts` (do not edit by hand)
 */
function main() {
  const webRoot = path.resolve(__dirname, '..');
  const dictionariesDir = path.join(webRoot, 'src', 'i18n', 'dictionaries');
  const outFile = path.join(webRoot, 'src', 'i18n', 'generated.ts');

  if (!fs.existsSync(dictionariesDir)) {
    throw new Error(`Missing dictionaries directory: ${dictionariesDir}`);
  }

  const localeFiles = fs
    .readdirSync(dictionariesDir, { withFileTypes: true })
    .filter((d) => d.isFile() && d.name.endsWith('.json'))
    .map((d) => d.name)
    .sort((a, b) => a.localeCompare(b));

  const locales = localeFiles
    .map((f) => path.basename(f, '.json'))
    .filter((l) => /^[a-z]{2}(-[a-z]{2})?$/i.test(l));

  if (locales.length === 0) {
    throw new Error(`No dictionary JSON files found in: ${dictionariesDir}`);
  }

  if (!locales.includes('en')) {
    throw new Error(`Default locale 'en' is required. Add en.json into ${dictionariesDir}`);
  }

  const importLines = locales.map((l) => `import ${toIdentifier(l)} from './dictionaries/${l}.json';`);

  const mapLines = locales.map((l) => `  '${l}': ${toIdentifier(l)} as Dictionary,`);

  const content = `/* eslint-disable */
/**
 * AUTO-GENERATED FILE. DO NOT EDIT.
 *
 * Generated by: scripts/generate-i18n.ts
 *
 * This file allows the app to be data-driven by JSON dictionaries while keeping
 * static imports (required for Next.js bundling).
 */

${importLines.join('\n')}

export type Dictionary = typeof en;

export const LOCALES = ${JSON.stringify(locales)} as const;
export type Locale = (typeof LOCALES)[number];

export const DICTIONARIES: Record<Locale, Dictionary> = {
${mapLines.join('\n')}
};
`;

  fs.writeFileSync(outFile, content, 'utf8');
}

function toIdentifier(locale: string) {
  // Convert e.g. "pt-br" => "ptBr", "en" => "en"
  const parts = locale.split(/[-_]/g);
  const [first, ...rest] = parts;
  return `${first.toLowerCase()}${rest.map((p) => p.charAt(0).toUpperCase() + p.slice(1).toLowerCase()).join('')}`;
}

/**
 * DEPRECATED.
 *
 * Docker/Node cannot execute `.ts` scripts without a loader.
 * Use `scripts/generate-i18n.mjs` instead.
 */

throw new Error('Deprecated: use scripts/generate-i18n.mjs');
