-- Migration 009: Update job posts with detailed content
-- Adds comprehensive responsibilities and requirements for all jobs

BEGIN;

-- ============================================================================
-- Update Job 1: NodeJS Developer - Senior (EN)
-- ============================================================================
UPDATE job_posts 
SET 
  summary = 'We are seeking an experienced Senior NodeJS Developer to join our dynamic engineering team. You will be responsible for designing and implementing scalable backend systems, leading technical initiatives, and mentoring junior developers.',
  responsibilities_md = E'- Design, document, and implement technical solutions for systems of various types and sizes, ensuring integration, maintenance, and migration considerations\n- Provide comprehensive software architecture design and lead technical decision-making processes\n- Manage code quality through rigorous code reviews, enforce coding standards, and ensure best practices\n- Define technical guidelines, review alternative approaches, and conduct thorough technical evaluations\n- Collaborate closely with product managers and lead engineers to recommend optimal solutions based on project roadmap\n- Work hands-on as a technical leader/expert architect in projects on a daily basis\n- Continuously stay informed on emerging technologies, frameworks, and tools\n- Develop new project ideas and proof-of-concepts when required by the project roadmap\n- Contribute to presales activities, including preparing technical proposals, effort estimations, and presenting solutions to clients\n- Support recruitment efforts within the company by conducting technical interviews and mentoring team members\n- Participate in architectural review boards and contribute to technology strategy discussions',
  requirements_md = E'- 7+ years of professional software development experience with C#, .NET, ASP.NET Core, Web API, Entity Framework, and SQL Server\n- Solid experience as Software Architect with deep understanding of design patterns, SOLID principles, and clean code practices\n- Strong expertise in database design, SQL optimization, and performance tuning\n- Hands-on experience with Azure or AWS cloud platforms, including services like App Services, Functions, Storage, and databases\n- Deep understanding of Microservices architecture, API Gateway patterns, and distributed systems\n- Experience with DevOps practices, CI/CD pipelines, and Infrastructure as Code (Terraform/ARM templates)\n- Strong focus on Performance optimization, Security best practices, and scalability considerations\n- Familiarity with frontend frameworks such as React, Angular, or Vue.js\n- Experience working and coordinating with global, distributed teams across different time zones\n- Excellent verbal and written communication skills in English\n- Comprehensive knowledge and expertise in Software Development Life Cycle (SDLC) methodologies\n- Experience with Agile/Scrum methodologies and tools like Jira, Confluence\n- Having experience with AI-powered development tools such as GitHub Copilot or similar is a strong plus\n- Bachelor''s degree in Computer Science, Software Engineering, or related field (Master''s preferred)'
WHERE slug = 'nodejs-developer-senior' AND locale = 'en';

-- ============================================================================
-- Update Job 1: NodeJS Developer - Senior (VI)
-- ============================================================================
UPDATE job_posts 
SET 
  summary = 'Chúng tôi đang tìm kiếm một Lập trình viên NodeJS Cấp cao có kinh nghiệm để tham gia đội ngũ kỹ thuật năng động của chúng tôi. Bạn sẽ chịu trách nhiệm thiết kế và triển khai các hệ thống backend có khả năng mở rộng, dẫn dắt các sáng kiến kỹ thuật và hướng dẫn các developer cấp thấp.',
  responsibilities_md = E'- Thiết kế, tài liệu hóa và triển khai các giải pháp kỹ thuật cho các hệ thống với nhiều loại và quy mô khác nhau, đảm bảo tích hợp, bảo trì và di chuyển\n- Cung cấp thiết kế kiến trúc phần mềm toàn diện và dẫn dắt các quyết định kỹ thuật\n- Quản lý chất lượng code thông qua review code nghiêm ngặt, thực thi coding standards và đảm bảo best practices\n- Xác định hướng dẫn kỹ thuật, đánh giá các phương pháp thay thế và thực hiện đánh giá kỹ thuật toàn diện\n- Cộng tác chặt chẽ với quản lý sản phẩm và kỹ sư trưởng để đề xuất giải pháp tối ưu dựa trên lộ trình dự án\n- Làm việc thực tế như một leader/expert architect hàng ngày trong các dự án\n- Liên tục cập nhật về công nghệ mới, framework và công cụ đang nổi lên\n- Phát triển ý tưởng dự án mới và proof-of-concept khi dự án yêu cầu\n- Đóng góp vào các hoạt động presales, bao gồm chuẩn bị đề xuất kỹ thuật, ước tính effort và trình bày giải pháp cho khách hàng\n- Hỗ trợ nỗ lực tuyển dụng trong công ty bằng cách thực hiện phỏng vấn kỹ thuật và hướng dẫn thành viên nhóm\n- Tham gia hội đồng đánh giá kiến trúc và đóng góp vào thảo luận chiến lược công nghệ',
  requirements_md = E'- 7+ năm kinh nghiệm phát triển phần mềm chuyên nghiệp với C#, .NET, ASP.NET Core, Web API, Entity Framework và SQL Server\n- Kinh nghiệm vững chắc với vai trò Software Architect với hiểu biết sâu về design patterns, SOLID principles và clean code practices\n- Chuyên môn mạnh về thiết kế database, tối ưu hóa SQL và performance tuning\n- Kinh nghiệm thực tế với các nền tảng cloud Azure hoặc AWS, bao gồm các dịch vụ như App Services, Functions, Storage và databases\n- Hiểu biết sâu về kiến trúc Microservices, API Gateway patterns và distributed systems\n- Kinh nghiệm với DevOps practices, CI/CD pipelines và Infrastructure as Code (Terraform/ARM templates)\n- Tập trung mạnh vào tối ưu hóa Performance, best practices về Security và cân nhắc về khả năng mở rộng\n- Quen thuộc với các frontend framework như React, Angular hoặc Vue.js\n- Kinh nghiệm làm việc và phối hợp với các đội ngũ toàn cầu, phân tán qua các múi giờ khác nhau\n- Kỹ năng giao tiếp bằng tiếng Anh xuất sắc cả nói và viết\n- Kiến thức và chuyên môn toàn diện về phương pháp Software Development Life Cycle (SDLC)\n- Kinh nghiệm với phương pháp Agile/Scrum và các công cụ như Jira, Confluence\n- Có kinh nghiệm với các công cụ phát triển hỗ trợ AI như GitHub Copilot hoặc tương tự là một lợi thế lớn\n- Bằng cử nhân Khoa học máy tính, Kỹ thuật phần mềm hoặc lĩnh vực liên quan (Thạc sĩ được ưu tiên)'
WHERE slug = 'lap-trinh-vien-nodejs-cap-cao' AND locale = 'vi';

-- ============================================================================
-- Update Job 2: Python Developer - Junior (EN)
-- ============================================================================
UPDATE job_posts 
SET 
  summary = 'Join our innovative team as a Junior Python Developer. This is an excellent opportunity for recent graduates or developers with 1-2 years of experience to grow their skills in a supportive environment while working on exciting projects.',
  responsibilities_md = E'- Develop, test, and maintain Python applications and scripts under senior developer guidance\n- Write clean, maintainable, and well-documented code following team standards and best practices\n- Collaborate with senior developers to design and implement new features\n- Participate actively in code reviews to learn best practices and improve code quality\n- Debug and troubleshoot application issues, proposing and implementing fixes\n- Create and maintain technical documentation for code and processes\n- Work with RESTful APIs and integrate third-party services\n- Write and maintain unit tests to ensure code reliability\n- Participate in daily stand-ups, sprint planning, and retrospectives\n- Learn and apply new technologies, frameworks, and tools as needed\n- Assist in database design and query optimization\n- Support senior developers in production deployments and monitoring',
  requirements_md = E'- 1-2 years of professional Python development experience or strong academic/personal project background\n- Basic understanding of web frameworks such as Django, Flask, or FastAPI\n- Familiarity with relational databases (PostgreSQL, MySQL) and basic SQL knowledge\n- Understanding of RESTful API concepts and JSON data formats\n- Basic knowledge of version control systems, particularly Git\n- Good problem-solving skills and ability to debug code effectively\n- Strong eagerness to learn new technologies and improve technical skills\n- Basic understanding of software development principles and best practices\n- Ability to work collaboratively in a team environment\n- Good communication skills in English (both written and verbal)\n- Basic knowledge of HTML, CSS, and JavaScript is a plus\n- Familiarity with Linux/Unix environments is advantageous\n- Experience with Docker or containerization is a plus\n- Bachelor''s degree in Computer Science, Software Engineering, or related field (or equivalent practical experience)'
WHERE slug = 'python-developer-junior' AND locale = 'en';

-- ============================================================================
-- Update Job 2: Python Developer - Junior (VI)
-- ============================================================================
UPDATE job_posts 
SET 
  summary = 'Tham gia đội ngũ sáng tạo của chúng tôi với vai trò Lập trình viên Python Sơ cấp. Đây là cơ hội tuyệt vời cho sinh viên mới tốt nghiệp hoặc developer có 1-2 năm kinh nghiệm để phát triển kỹ năng trong môi trường hỗ trợ tốt trong khi làm việc trên các dự án thú vị.',
  responsibilities_md = E'- Phát triển, kiểm thử và bảo trì các ứng dụng và script Python dưới sự hướng dẫn của developer cấp cao\n- Viết code sạch, dễ bảo trì và có tài liệu tốt theo tiêu chuẩn và best practices của team\n- Cộng tác với developer cấp cao để thiết kế và triển khai các tính năng mới\n- Tham gia tích cực vào code review để học best practices và cải thiện chất lượng code\n- Debug và khắc phục sự cố ứng dụng, đề xuất và triển khai các giải pháp sửa lỗi\n- Tạo và duy trì tài liệu kỹ thuật cho code và quy trình\n- Làm việc với RESTful APIs và tích hợp các dịch vụ bên thứ ba\n- Viết và duy trì unit tests để đảm bảo độ tin cậy của code\n- Tham gia daily stand-ups, sprint planning và retrospectives\n- Học và áp dụng công nghệ, framework và công cụ mới khi cần thiết\n- Hỗ trợ trong thiết kế database và tối ưu hóa query\n- Hỗ trợ developer cấp cao trong việc triển khai production và giám sát',
  requirements_md = E'- 1-2 năm kinh nghiệm phát triển Python chuyên nghiệp hoặc nền tảng dự án học thuật/cá nhân mạnh\n- Hiểu biết cơ bản về các web framework như Django, Flask hoặc FastAPI\n- Quen thuộc với relational databases (PostgreSQL, MySQL) và kiến thức SQL cơ bản\n- Hiểu biết về khái niệm RESTful API và format dữ liệu JSON\n- Kiến thức cơ bản về hệ thống version control, đặc biệt là Git\n- Kỹ năng giải quyết vấn đề tốt và khả năng debug code hiệu quả\n- Háo hức học hỏi công nghệ mới và cải thiện kỹ năng kỹ thuật\n- Hiểu biết cơ bản về nguyên tắc và best practices phát triển phần mềm\n- Khả năng làm việc cộng tác trong môi trường nhóm\n- Kỹ năng giao tiếp tiếng Anh tốt (cả viết và nói)\n- Kiến thức cơ bản về HTML, CSS và JavaScript là một lợi thế\n- Quen thuộc với môi trường Linux/Unix là thuận lợi\n- Kinh nghiệm với Docker hoặc containerization là một lợi thế\n- Bằng cử nhân Khoa học máy tính, Kỹ thuật phần mềm hoặc lĩnh vực liên quan (hoặc kinh nghiệm thực tế tương đương)'
WHERE slug = 'lap-trinh-vien-python-so-cap' AND locale = 'vi';

-- ============================================================================
-- Update Job 3: Data Scientist Lead (EN)
-- ============================================================================
UPDATE job_posts 
SET 
  summary = 'We are looking for an experienced Data Scientist Lead to drive our data science initiatives and build machine learning models that deliver real business impact. You will lead a team of data scientists and work closely with stakeholders across the organization.',
  responsibilities_md = E'- Lead and mentor a team of data scientists, fostering a culture of innovation and continuous learning\n- Design, develop, and deploy machine learning models and algorithms to solve complex business problems\n- Collaborate with business stakeholders to identify opportunities for leveraging data to drive business solutions\n- Define and implement data science strategy aligned with company objectives\n- Conduct advanced statistical analysis and build predictive models using large datasets\n- Design and implement A/B testing frameworks and experimentation processes\n- Develop data pipelines and automation tools for model training and deployment\n- Communicate complex analytical findings to non-technical stakeholders through compelling visualizations and presentations\n- Stay current with latest developments in data science, machine learning, and AI technologies\n- Establish best practices for data science workflows, model versioning, and deployment\n- Partner with engineering teams to productionize ML models at scale\n- Drive data-driven decision making across the organization\n- Manage multiple projects simultaneously while ensuring quality and timely delivery',
  requirements_md = E'- 5+ years of experience in data science, machine learning, or related analytical roles\n- Strong proficiency in Python and R for data analysis and model development\n- Deep understanding of machine learning algorithms, statistical methods, and their applications\n- Extensive experience with ML frameworks such as TensorFlow, PyTorch, scikit-learn, or XGBoost\n- Expert-level SQL skills for complex data extraction and manipulation\n- Experience with big data technologies (Spark, Hadoop, etc.) is highly valued\n- Strong knowledge of data visualization tools (Tableau, PowerBI, Plotly) and techniques\n- Proven track record of deploying ML models to production environments\n- Experience with cloud platforms (AWS SageMaker, Azure ML, or Google Cloud AI)\n- 2+ years of leadership experience managing and mentoring data science teams\n- Excellent communication and presentation skills, able to explain complex concepts to diverse audiences\n- Strong business acumen and ability to translate business problems into analytical solutions\n- Experience with MLOps practices and tools (MLflow, Kubeflow, etc.)\n- Master''s degree or PhD in Computer Science, Statistics, Mathematics, or related quantitative field preferred\n- Publications or contributions to open-source data science projects are a plus'
WHERE slug = 'data-scientist-lead' AND locale = 'en';

-- ============================================================================
-- Update Job 3: Data Scientist Lead (VI)
-- ============================================================================
UPDATE job_posts 
SET 
  summary = 'Chúng tôi đang tìm kiếm một Trưởng nhóm Khoa học dữ liệu có kinh nghiệm để thúc đẩy các sáng kiến khoa học dữ liệu và xây dựng các mô hình machine learning mang lại tác động kinh doanh thực sự. Bạn sẽ dẫn dắt một nhóm data scientists và làm việc chặt chẽ với các bên liên quan trong toàn tổ chức.',
  responsibilities_md = E'- Dẫn dắt và hướng dẫn một nhóm data scientists, nuôi dưỡng văn hóa đổi mới và học hỏi liên tục\n- Thiết kế, phát triển và triển khai các mô hình và thuật toán machine learning để giải quyết các vấn đề kinh doanh phức tạp\n- Cộng tác với các bên liên quan kinh doanh để xác định cơ hội tận dụng dữ liệu nhằm thúc đẩy giải pháp kinh doanh\n- Xác định và triển khai chiến lược data science phù hợp với mục tiêu công ty\n- Thực hiện phân tích thống kê nâng cao và xây dựng mô hình dự đoán sử dụng tập dữ liệu lớn\n- Thiết kế và triển khai framework A/B testing và quy trình thử nghiệm\n- Phát triển data pipelines và công cụ tự động hóa cho training và deployment mô hình\n- Truyền đạt các phát hiện phân tích phức tạp cho các bên liên quan phi kỹ thuật thông qua trực quan hóa và trình bày hấp dẫn\n- Cập nhật với các phát triển mới nhất trong data science, machine learning và công nghệ AI\n- Thiết lập best practices cho quy trình data science, model versioning và deployment\n- Hợp tác với đội ngũ engineering để productionize các mô hình ML ở quy mô lớn\n- Thúc đẩy ra quyết định dựa trên dữ liệu trong toàn tổ chức\n- Quản lý nhiều dự án đồng thời trong khi đảm bảo chất lượng và giao hàng đúng hạn',
  requirements_md = E'- 5+ năm kinh nghiệm trong data science, machine learning hoặc các vai trò phân tích liên quan\n- Thành thạo Python và R cho phân tích dữ liệu và phát triển mô hình\n- Hiểu biết sâu về các thuật toán machine learning, phương pháp thống kê và ứng dụng của chúng\n- Kinh nghiệm rộng rãi với các framework ML như TensorFlow, PyTorch, scikit-learn hoặc XGBoost\n- Kỹ năng SQL ở cấp độ chuyên gia cho trích xuất và xử lý dữ liệu phức tạp\n- Kinh nghiệm với các công nghệ big data (Spark, Hadoop, v.v.) được đánh giá cao\n- Kiến thức mạnh về các công cụ (Tableau, PowerBI, Plotly) và kỹ thuật trực quan hóa dữ liệu\n- Hồ sơ đã được chứng minh về việc triển khai mô hình ML vào môi trường production\n- Kinh nghiệm với các nền tảng cloud (AWS SageMaker, Azure ML hoặc Google Cloud AI)\n- 2+ năm kinh nghiệm lãnh đạo quản lý và hướng dẫn các nhóm data science\n- Kỹ năng giao tiếp và trình bày xuất sắc, có thể giải thích các khái niệm phức tạp cho nhiều đối tượng khác nhau\n- Nhận thức kinh doanh mạnh và khả năng chuyển đổi các vấn đề kinh doanh thành giải pháp phân tích\n- Kinh nghiệm với các thực hành và công cụ MLOps (MLflow, Kubeflow, v.v.)\n- Bằng thạc sĩ hoặc tiến sĩ về Khoa học máy tính, Thống kê, Toán học hoặc lĩnh vực định lượng liên quan được ưu tiên\n- Các xuất bản hoặc đóng góp cho các dự án data science mã nguồn mở là một lợi thế'
WHERE slug = 'truong-nhom-khoa-hoc-du-lieu' AND locale = 'vi';

-- ============================================================================
-- Update Job 4: Solution Architect - .NET (EN)
-- ============================================================================
UPDATE job_posts 
SET 
  summary = 'We are seeking a highly skilled Solution Architect with deep .NET expertise to design enterprise-grade solutions and lead technical teams. You will be responsible for architecting scalable systems and driving technical excellence across the organization.',
  responsibilities_md = E'- Design and architect scalable, secure, and high-performance enterprise solutions using .NET technologies\n- Lead technical decision-making processes and define technology strategies for complex projects\n- Provide technical leadership and mentorship to development teams across multiple projects\n- Conduct architecture reviews, technical assessments, and recommend improvements to existing systems\n- Create and maintain comprehensive technical documentation including architecture diagrams, design documents, and technical specifications\n- Collaborate with stakeholders, product managers, and business analysts to translate business requirements into technical solutions\n- Define and enforce architectural standards, best practices, and coding guidelines across the organization\n- Evaluate and recommend new technologies, frameworks, and tools to improve development efficiency and system performance\n- Lead proof-of-concept initiatives to validate architectural decisions and new technology adoption\n- Design and implement integration strategies for complex systems and third-party services\n- Ensure solutions meet non-functional requirements including security, performance, scalability, and maintainability\n- Participate in pre-sales activities, including solution presentations and technical proposals for clients\n- Conduct technical training sessions and knowledge sharing workshops for development teams\n- Monitor industry trends and emerging technologies in the .NET ecosystem and cloud platforms',
  requirements_md = E'- 10+ years of professional software development experience with strong focus on .NET technologies (C#, ASP.NET Core, .NET 6+)\n- 5+ years of experience in solution architecture or technical leadership roles\n- Deep expertise in software architecture patterns (microservices, event-driven, CQRS, DDD, hexagonal architecture)\n- Extensive experience with cloud platforms, particularly Azure (Azure Functions, App Services, AKS, Service Bus, Cosmos DB)\n- Strong knowledge of AWS services and multi-cloud architecture strategies\n- Expert understanding of API design, RESTful services, GraphQL, and API management\n- Deep knowledge of database technologies (SQL Server, PostgreSQL, MongoDB, Redis) and data architecture\n- Extensive experience with containerization (Docker) and orchestration (Kubernetes)\n- Strong expertise in DevOps practices, CI/CD pipelines (Azure DevOps, GitHub Actions), and Infrastructure as Code\n- Experience with message queuing systems (RabbitMQ, Azure Service Bus, Kafka)\n- Deep understanding of security best practices, OAuth2, JWT, and identity management solutions\n- Proven experience in performance optimization, system scalability, and handling high-traffic applications\n- Strong leadership skills with experience mentoring and guiding development teams\n- Excellent communication and presentation skills, able to articulate complex technical concepts to both technical and non-technical audiences\n- Experience with Agile/Scrum methodologies and leading technical aspects of agile teams\n- Relevant certifications such as Microsoft Certified: Azure Solutions Architect Expert are highly valued\n- Bachelor''s or Master''s degree in Computer Science, Software Engineering, or related field'
WHERE slug = 'solution-architect-dotnet' AND locale = 'en';

-- ============================================================================
-- Update Job 4: Solution Architect - .NET (VI)
-- ============================================================================
UPDATE job_posts 
SET 
  summary = 'Chúng tôi đang tìm kiếm một Kiến trúc sư giải pháp có kỹ năng cao với chuyên môn .NET sâu rộng để thiết kế các giải pháp cấp doanh nghiệp và dẫn dắt các đội ngũ kỹ thuật. Bạn sẽ chịu trách nhiệm thiết kế kiến trúc các hệ thống có khả năng mở rộng và thúc đẩy sự xuất sắc kỹ thuật trong toàn tổ chức.',
  responsibilities_md = E'- Thiết kế và kiến trúc các giải pháp doanh nghiệp có khả năng mở rộng, bảo mật và hiệu suất cao sử dụng công nghệ .NET\n- Dẫn dắt các quy trình ra quyết định kỹ thuật và xác định chiến lược công nghệ cho các dự án phức tạp\n- Cung cấp lãnh đạo kỹ thuật và hướng dẫn cho các đội phát triển trên nhiều dự án\n- Thực hiện đánh giá kiến trúc, đánh giá kỹ thuật và đề xuất cải tiến cho các hệ thống hiện có\n- Tạo và duy trì tài liệu kỹ thuật toàn diện bao gồm sơ đồ kiến trúc, tài liệu thiết kế và đặc tả kỹ thuật\n- Cộng tác với các bên liên quan, quản lý sản phẩm và business analysts để chuyển đổi yêu cầu kinh doanh thành giải pháp kỹ thuật\n- Xác định và thực thi tiêu chuẩn kiến trúc, best practices và coding guidelines trong toàn tổ chức\n- Đánh giá và đề xuất công nghệ, framework và công cụ mới để cải thiện hiệu quả phát triển và hiệu suất hệ thống\n- Dẫn dắt các sáng kiến proof-of-concept để xác thực quyết định kiến trúc và áp dụng công nghệ mới\n- Thiết kế và triển khai chiến lược tích hợp cho các hệ thống phức tạp và dịch vụ bên thứ ba\n- Đảm bảo các giải pháp đáp ứng yêu cầu phi chức năng bao gồm bảo mật, hiệu suất, khả năng mở rộng và dễ bảo trì\n- Tham gia vào các hoạt động pre-sales, bao gồm trình bày giải pháp và đề xuất kỹ thuật cho khách hàng\n- Thực hiện các buổi đào tạo kỹ thuật và workshop chia sẻ kiến thức cho các đội phát triển\n- Theo dõi xu hướng ngành và công nghệ mới nổi trong hệ sinh thái .NET và nền tảng cloud',
  requirements_md = E'- 10+ năm kinh nghiệm phát triển phần mềm chuyên nghiệp với trọng tâm mạnh vào công nghệ .NET (C#, ASP.NET Core, .NET 6+)\n- 5+ năm kinh nghiệm trong vai trò solution architecture hoặc technical leadership\n- Chuyên môn sâu về các mẫu kiến trúc phần mềm (microservices, event-driven, CQRS, DDD, hexagonal architecture)\n- Kinh nghiệm rộng rãi với các nền tảng cloud, đặc biệt là Azure (Azure Functions, App Services, AKS, Service Bus, Cosmos DB)\n- Kiến thức mạnh về các dịch vụ AWS và chiến lược kiến trúc multi-cloud\n- Hiểu biết chuyên sâu về thiết kế API, RESTful services, GraphQL và API management\n- Kiến thức sâu về công nghệ database (SQL Server, PostgreSQL, MongoDB, Redis) và kiến trúc dữ liệu\n- Kinh nghiệm rộng rãi với containerization (Docker) và orchestration (Kubernetes)\n- Chuyên môn mạnh về DevOps practices, CI/CD pipelines (Azure DevOps, GitHub Actions) và Infrastructure as Code\n- Kinh nghiệm với các hệ thống message queuing (RabbitMQ, Azure Service Bus, Kafka)\n- Hiểu biết sâu về best practices bảo mật, OAuth2, JWT và giải pháp identity management\n- Kinh nghiệm đã được chứng minh trong tối ưu hóa hiệu suất, khả năng mở rộng hệ thống và xử lý ứng dụng lưu lượng cao\n- Kỹ năng lãnh đạo mạnh với kinh nghiệm hướng dẫn và dẫn dắt các đội phát triển\n- Kỹ năng giao tiếp và trình bày xuất sắc, có thể diễn đạt các khái niệm kỹ thuật phức tạp cho cả đối tượng kỹ thuật và phi kỹ thuật\n- Kinh nghiệm với phương pháp Agile/Scrum và dẫn dắt các khía cạnh kỹ thuật của agile teams\n- Các chứng chỉ liên quan như Microsoft Certified: Azure Solutions Architect Expert được đánh giá cao\n- Bằng cử nhân hoặc thạc sĩ về Khoa học máy tính, Kỹ thuật phần mềm hoặc lĩnh vực liên quan'
WHERE slug = 'kien-truc-su-giai-phap-dotnet' AND locale = 'vi';

-- ============================================================================
-- Update Job 5: AI Engineer - Master (EN)
-- ============================================================================
UPDATE job_posts 
SET 
  summary = 'Join our AI team as a Master AI Engineer to build cutting-edge artificial intelligence solutions that push the boundaries of what''s possible. You will lead AI initiatives, research new methodologies, and deploy production-grade ML systems at scale.',
  responsibilities_md = E'- Design, develop, and deploy state-of-the-art AI and machine learning systems for real-world business applications\n- Lead AI research and development initiatives, exploring new algorithms, models, and techniques\n- Architect and implement end-to-end ML pipelines from data ingestion to model deployment and monitoring\n- Mentor and guide AI/ML engineers and data scientists, fostering a culture of innovation and technical excellence\n- Stay at the forefront of AI research, continuously evaluating and adopting latest advancements in deep learning, NLP, computer vision, and reinforcement learning\n- Collaborate with product teams to identify opportunities where AI can create significant business value\n- Design and implement scalable ML infrastructure and MLOps workflows for model training, versioning, and deployment\n- Conduct technical reviews and ensure AI solutions meet high standards of performance, reliability, and ethical considerations\n- Optimize model performance for production environments, balancing accuracy, latency, and computational costs\n- Develop frameworks and tools to accelerate AI development across the organization\n- Lead technical discussions with stakeholders, translating complex AI concepts into business value propositions\n- Contribute to open-source AI projects and publish research findings in relevant conferences or journals\n- Establish best practices for responsible AI development, including fairness, transparency, and bias mitigation\n- Design and implement A/B testing frameworks to measure AI model impact on business metrics',
  requirements_md = E'- Master''s degree or PhD in Computer Science, Artificial Intelligence, Machine Learning, or related quantitative field\n- 8+ years of hands-on experience in AI/ML engineering with proven track record of deploying production ML systems\n- Deep expertise in deep learning frameworks (TensorFlow, PyTorch, JAX) and neural network architectures\n- Strong foundation in machine learning theory, algorithms, and statistical methods\n- Extensive experience with NLP (transformers, BERT, GPT, etc.) and/or computer vision (CNNs, object detection, segmentation)\n- Proficiency in Python and ML libraries (NumPy, Pandas, Scikit-learn, Hugging Face)\n- Experience with distributed training, model optimization, and serving at scale\n- Strong knowledge of MLOps tools and practices (MLflow, Kubeflow, Weights & Biases, etc.)\n- Hands-on experience with cloud ML platforms (AWS SageMaker, Azure ML, Google Vertex AI)\n- Experience with vector databases and embeddings for RAG (Retrieval Augmented Generation) applications\n- Strong understanding of model monitoring, A/B testing, and continuous model improvement\n- Experience with containerization (Docker) and orchestration (Kubernetes) for ML workloads\n- Proven ability to work with large-scale datasets and big data technologies (Spark, Hadoop)\n- Strong programming skills with focus on writing production-quality, maintainable code\n- Experience leading technical teams and mentoring junior engineers\n- Excellent communication skills with ability to explain complex AI concepts to diverse audiences\n- Publications in top-tier AI/ML conferences (NeurIPS, ICML, CVPR) or significant contributions to open-source AI projects are highly valued\n- Track record of innovation and staying current with rapidly evolving AI landscape'
WHERE slug = 'ai-engineer-master' AND locale = 'en';

-- ============================================================================
-- Update Job 5: AI Engineer - Master (VI)
-- ============================================================================
UPDATE job_posts 
SET 
  summary = 'Tham gia đội AI của chúng tôi với vai trò Kỹ sư AI Chuyên gia để xây dựng các giải pháp trí tuệ nhân tạo tiên tiến vượt qua ranh giới của những gì có thể. Bạn sẽ dẫn dắt các sáng kiến AI, nghiên cứu phương pháp mới và triển khai các hệ thống ML cấp production ở quy mô lớn.',
  responsibilities_md = E'- Thiết kế, phát triển và triển khai các hệ thống AI và machine learning tiên tiến nhất cho các ứng dụng kinh doanh thực tế\n- Dẫn dắt các sáng kiến nghiên cứu và phát triển AI, khám phá các thuật toán, mô hình và kỹ thuật mới\n- Thiết kế kiến trúc và triển khai ML pipelines từ đầu đến cuối từ thu thập dữ liệu đến triển khai và giám sát mô hình\n- Hướng dẫn và dẫn dắt các AI/ML engineers và data scientists, nuôi dưỡng văn hóa đổi mới và sự xuất sắc kỹ thuật\n- Luôn đi đầu trong nghiên cứu AI, liên tục đánh giá và áp dụng những tiến bộ mới nhất trong deep learning, NLP, computer vision và reinforcement learning\n- Cộng tác với các đội sản phẩm để xác định cơ hội mà AI có thể tạo ra giá trị kinh doanh đáng kể\n- Thiết kế và triển khai cơ sở hạ tầng ML có khả năng mở rộng và quy trình MLOps cho training, versioning và deployment mô hình\n- Thực hiện đánh giá kỹ thuật và đảm bảo các giải pháp AI đáp ứng tiêu chuẩn cao về hiệu suất, độ tin cậy và cân nhắc đạo đức\n- Tối ưu hóa hiệu suất mô hình cho môi trường production, cân bằng độ chính xác, độ trễ và chi phí tính toán\n- Phát triển frameworks và công cụ để tăng tốc phát triển AI trong toàn tổ chức\n- Dẫn dắt các cuộc thảo luận kỹ thuật với các bên liên quan, chuyển đổi các khái niệm AI phức tạp thành đề xuất giá trị kinh doanh\n- Đóng góp cho các dự án AI mã nguồn mở và xuất bản các phát hiện nghiên cứu tại các hội nghị hoặc tạp chí liên quan\n- Thiết lập best practices cho phát triển AI có trách nhiệm, bao gồm công bằng, minh bạch và giảm thiểu bias\n- Thiết kế và triển khai framework A/B testing để đo lường tác động của mô hình AI đến các chỉ số kinh doanh',
  requirements_md = E'- Bằng thạc sĩ hoặc tiến sĩ về Khoa học máy tính, Trí tuệ nhân tạo, Machine Learning hoặc lĩnh vực định lượng liên quan\n- 8+ năm kinh nghiệm thực tế trong kỹ thuật AI/ML với hồ sơ đã được chứng minh về việc triển khai hệ thống ML production\n- Chuyên môn sâu về các framework deep learning (TensorFlow, PyTorch, JAX) và kiến trúc neural network\n- Nền tảng vững chắc về lý thuyết machine learning, thuật toán và phương pháp thống kê\n- Kinh nghiệm rộng rãi với NLP (transformers, BERT, GPT, v.v.) và/hoặc computer vision (CNNs, object detection, segmentation)\n- Thành thạo Python và các thư viện ML (NumPy, Pandas, Scikit-learn, Hugging Face)\n- Kinh nghiệm với distributed training, tối ưu hóa mô hình và serving ở quy mô lớn\n- Kiến thức mạnh về các công cụ và thực hành MLOps (MLflow, Kubeflow, Weights & Biases, v.v.)\n- Kinh nghiệm thực tế với các nền tảng cloud ML (AWS SageMaker, Azure ML, Google Vertex AI)\n- Kinh nghiệm với vector databases và embeddings cho các ứng dụng RAG (Retrieval Augmented Generation)\n- Hiểu biết mạnh về model monitoring, A/B testing và cải tiến mô hình liên tục\n- Kinh nghiệm với containerization (Docker) và orchestration (Kubernetes) cho ML workloads\n- Khả năng đã được chứng minh làm việc với tập dữ liệu quy mô lớn và công nghệ big data (Spark, Hadoop)\n- Kỹ năng lập trình mạnh với trọng tâm vào viết code chất lượng production, dễ bảo trì\n- Kinh nghiệm dẫn dắt các đội kỹ thuật và hướng dẫn các kỹ sư cấp thấp\n- Kỹ năng giao tiếp xuất sắc với khả năng giải thích các khái niệm AI phức tạp cho nhiều đối tượng khác nhau\n- Các xuất bản tại các hội nghị AI/ML hàng đầu (NeurIPS, ICML, CVPR) hoặc đóng góp đáng kể cho các dự án AI mã nguồn mở được đánh giá cao\n- Hồ sơ đổi mới và cập nhật với bối cảnh AI phát triển nhanh chóng'
WHERE slug = 'ky-su-ai-chuyen-gia' AND locale = 'vi';

COMMIT;
