-- Migration: Create email_notifications table
-- Purpose: Track all email notifications sent from the system
-- Created: 2026-01-30

-- Email notification status enum
CREATE TYPE email_status AS ENUM ('pending', 'sent', 'failed');

-- Email notification type enum
CREATE TYPE email_type AS ENUM ('lead_notification', 'job_application', 'system');

-- Email notifications table
CREATE TABLE "email_notifications" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "type" email_type NOT NULL,
  "recipient" text NOT NULL,
  "subject" text NOT NULL,
  "body" text NOT NULL,
  "status" email_status NOT NULL DEFAULT 'pending',
  "error_message" text,
  "metadata" jsonb,
  "sent_at" timestamptz,
  "created_at" timestamptz NOT NULL DEFAULT (now())
);

-- Index for querying by status and type
CREATE INDEX idx_email_notifications_status ON email_notifications(status);
CREATE INDEX idx_email_notifications_type ON email_notifications(type);
CREATE INDEX idx_email_notifications_created_at ON email_notifications(created_at DESC);
