-- Migration 021: Add pgvector extension and content_embeddings table for RAG chatbot
-- Run: psql -d koola_db -f migrations/021_add_chat_embeddings.sql

CREATE EXTENSION IF NOT EXISTS vector;

CREATE TABLE IF NOT EXISTS "content_embeddings" (
  "id"          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "source_type" text NOT NULL,
  "source_id"   bigint,
  "locale"      text NOT NULL DEFAULT 'en',
  "chunk_index" int NOT NULL DEFAULT 0,
  "chunk_text"  text NOT NULL,
  "embedding"   vector(768),
  "metadata"    jsonb NOT NULL DEFAULT '{}',
  "created_at"  timestamptz NOT NULL DEFAULT now(),
  "updated_at"  timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_embeddings_source
  ON content_embeddings (source_type, source_id, locale, chunk_index);

CREATE INDEX IF NOT EXISTS idx_embeddings_vector
  ON content_embeddings USING ivfflat (embedding vector_cosine_ops) WITH (lists = 50);

CREATE INDEX IF NOT EXISTS idx_embeddings_source_locale
  ON content_embeddings (source_type, locale);
