/* eslint-disable */
/**
 * AUTO-GENERATED FILE. DO NOT EDIT.
 *
 * Generated by: scripts/generate-i18n.mjs
 *
 * This file allows the app to be data-driven by JSON dictionaries while keeping
 * static imports (required for Next.js bundling).
 */

import en from './dictionaries/en.json';
import vi from './dictionaries/vi.json';

export type Dictionary = typeof en;

export const LOCALES = ["en","vi"] as const;
export type Locale = (typeof LOCALES)[number];

export const DICTIONARIES: Record<Locale, Dictionary> = {
  'en': en as Dictionary,
  'vi': vi as Dictionary,
};
